"""empty message

Revision ID: b44871c99639
Revises: 8bdf49853785
Create Date: 2026-04-06 22:47:53.968419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44871c99639'
down_revision = '8bdf49853785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('room_description', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('room_description')
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###
